---
title: "Version 1.1 beta"
output: 
  html_document:
    highlight: tango
    number_sections: no
    theme: united
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: yes
      smooth_scroll: yes

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = F)
```

NEW VERSION (1.1) OF HARMONISED DATASETS ARE READY IN OPAL 

CHANGES FROM PREVIOUS VERSION (1.0) ARE DESCRIBED BELOW.

# Changes

## Socio-demographic and economic characteristics

### Age

 + Harmonised variable: `dbirth`,`mbirth`
 + Study: `CHARLS`
 + Waves: all
 + Changes: correction in the algorithm: `0` recodified as 998.

 + Harmonised variable: `dbirth`,`mbirth`,`ybirth`
 + Study: `MHAS`
 + Waves: all
 + Changes: corrections in the algorithms: added the study-specific variables `aa2_1`, `aa2_1_12`, `a2a2_1_12`, `aa2_2`,`aa2_2_12`,`a2a2_2_12` and `aa2_3`,`aa2_3_12`,`a2a2_3_12` respectively, together with `a2a1_12`.

### Education

 + Harmonised variable: `education`
 + Study: `HRS`,`HEALTH_2000`
 + Waves: all
 + Changes: correction in the algorithms: new recodification of values of `RAEDUC` (`HRS`), and `AC01` and `AC02` (`HEALTH_2000`)

### Wealth

 + Harmonised variable: `wealth`
 + Study: `ELSA`
 + Waves: 1
 + Changes: correction of data loaded (table `wave_1_financial_derived_variables` with original data updated).

## Lifestyle and health behaviours

### Tobacco

 + Harmonised variable: `current_smoking`
 + Study: `ALSA`
 + Waves: 6 and 7
 + Changes: correction in the algorithm: 0 recodified as 995.

 + Harmonised variable: `current_smoking`,`smoking`
 + Study: `ELSA`
 + Waves: essentially all.
 + Changes: correction in the algorithm: `-2 = not asked` recodified as 994.

 + Harmonised variable: `ever_smoked`
 + Study: `ALSA`
 + Waves: 1
 + Changes: correction in the algorithm: `SMOKER` == 2 and `REGSMKPS` == 2 and `REGPIPCG` == 2 or 99 into 0.

 + Harmonised variable: `n_cigarettes`
 + Study: `ALSA`
 + Waves: 7
 + Changes: correction in the algorithm: 99 recodified as 0 and 0 recodified as 995.

 + Harmonised variable: `n_cigarettes`
 + Study: `ALSA`
 + Waves: 11
 + Changes: it is not harmonised, since the study-specific variable only contains one non-missing value.
 
 + Harmonised variable: `n_cigarettes`
 + Study: `ELSA`
 + Waves: essentially all.
 + Changes: minor corrections in the algorithm: specific cases treated.

 + Harmonised variable: `n_cigarettes`
 + Study: `HAPIEE`
 + Waves: all
 + Changes: correction in the algorithm: taken into account non-smoking conditions.


### Physical activity

 + Harmonised variable: `t_walks`
 + Study: `ALSA`
 + Waves: 6, 7, 8 and 9
 + Changes: correction in the algorithm: 0 recodified as 995.

 + Harmonised variable: `f_mod_pa`
 + Study: `ALSA`,`CHARLS`, `COURAGE`,`HRS`,`HEALTH_2000`,`SAGE`
 + Waves: all
 + Changes: Harmonised and saved.

 + Harmonised variable: `vig_pa`,`f_vig_pa`,`n_vig_pa`,`t_vig_pa`
 + Study: all
 + Waves: all
 + Changes: Harmonised and saved.

## Health status and functional limitations


### Health metric

 + Harmonised variable: `incontinence`
 + Study: `TILDA`
 + Waves: Wave 2
 + Changes: correction in the algorithm: category 5 recodified as 1 (`No`).

 + Harmonised variable: `healthstatus`
 + Study: all except `ATTICA` and `UBCoS`
 + Waves: all
 + Changes: Harmonised and saved.

 + Harmonised variable: `healthstatus`
 + Study: `SHARE`
 + Waves: 3
 + Changes: removed id's extra not appearing in any other table and whose values are all missing.

### Self reported health

 + Harmonised variable: `srh`
 + Study: `ELSA`
 + Waves: 1
 + Changes: correction in the algorithm: added variable `hegenh`.


## Diseases

 + Harmonised variable: `cd_all`
 + Study: `SAGE`
 + Waves: all
 + Changes: removed. It is not a harmonised variable.


## Death

 + Harmonised variable: `ydeath`,`living_status`
 + Study: `ELSA`
 + Waves: 2,3,4
 + Changes: 3 id's which only appear in tables used exclusively for these variables are removed (`115040`,`101432` and `114235`; resp. `athlos_id` `06-01-12208`,`06-01-13949` and `06-01-16631`). They correspond to individuals of wave 0 of ELSA which do not entry in any following wave untill they are dead.

 + Harmonised variable: all.
 + Study: `MHAS`
 + Waves: 3
 + Changes: 4 id's which only appear in wave 3 and they do as dead individual are removed. Further, there is almost no data about them.
 
 
 + Harmonised variable: `living_status`
 + Study: `HRS`
 + Waves: all
 + Changes: correction in the algorithm: some individuals with paradoxical data recategorized as `dead`.


## Physical measures

 + Harmonised variable: `ah`
 + Study: `SAGE`
 + Waves: Mexico - Wave 1
 + Changes: correction of data loaded.

## Psychological measures

 + Harmonised variable: `depression`
 + Study: `ENRICA`
 + Waves: all
 + Changes: Harmonised and saved.

## Laboratory measures

 + Harmonised variable: Laboratory measures variables (`glucose`,`fibrinogen`,`triglycerides`,`hdl_chol`,`ldl_chol`,`total_chol`,`crp`)
 + Study: all for which the variables exist (`ATTICA`,`ELSA`,`ENRICA`,`HAPIEE`,`HEALTH_2000`,`MHAS`,`TILDA`)
 + Waves: all
 + Changes: Harmonised and saved.

## Social environment

### Social network

 + Harmonised variable: `spouse`
 + Study: `SHARE`
 + Waves: Wave 3
 + Changes: Harmonised (correction in the algorithm; cf. Quality estimation) and saved.

 + Harmonised variable: `child`
 + Study: `MHAS`
 + Waves: Wave 2
 + Changes: added the study-specific variables `aa20` and `d4` and used in the harmonization algorithm.

 + Harmonised variable: `grchild`
 + Study: `MHAS`
 + Waves: all
 + Changes: Harmonised and saved.

 + Harmonised variable: `cont_fr`
 + Study: `10/66`,`COURAGE`,`ELSA`,`LASI`
 + Waves: all
 + Changes: correction in the algorithm: `no friends` recodified as 0 (`No contacts wit friends`).

 + Harmonised variable: `cont_fr`
 + Study: `HAPIEE`
 + Waves: Lithuania - Wave 1
 + Changes: correction in the algorithm: `.b`,`.c` recodified as 997 and 998 respectively.

 + Harmonised variable: `cont_fr`
 + Study: `MHAS`
 + Waves: Wave 2
 + Changes: Harmonised and saved.

 + Harmonised variable: `cont_fr`
 + Study: `TILDA`
 + Waves: Wave 1
 + Changes: correction in the algorithm: `-812,-823,-834`,`-845.-856.-867.-878` recodified as 1 and 0 respectively.

 + Harmonised variable: `cont_rel`
 + Study: `MHAS`
 + Waves: all
 + Changes: Harmonised and saved.


### Social support

 + Harmonised variable: `inst_sup`
 + Study: `MHAS`
 + Waves: all
 + Changes: Harmonised and saved.

 + Harmonised variable: `close_spouse`
 + Study: all for which the variable exists (`ALSA`,`COURAGE`,`ELSA`,`JSTAR`,`LASI`,`TILDA`)
 + Waves: all
 + Changes: Harmonised and saved.

 + Harmonised variable: `emot_sup`
 + Study: all for which the variable exists (`ALSA`,`COURAGE`,`ELSA`,`ENRICA`,`HAPIEE`,`HEALTH_2000`,`JSTAR`,`SAGE`,`TILDA`)
 + Waves: all
 + Changes: Harmonised and saved.


### Social participation

 + Harmonised variable: `pol_act`
 + Study: `ELSA`
 + Waves: Wave 7
 + Changes: RData corrected.

 + Harmonised variable: `pol_vot`
 + Study: all for which the variable exists (`COURAGE`,`ELSA`,`LASI`,`SAGE`,`TILDA`)
 + Waves: all
 + Changes: Harmonised and saved.

 + Harmonised variable: `part_clubs`
 + Study: all for which the variable exists (`10/66`,`ALSA`,`CHARLS`,`COURAGE`,`ELSA`,`HAPIEE`,`JSTAR`,`KLOSA`,`LASI`,`SAGE`,`SHARE`,`TILDA`)
 + Waves: all
 + Changes: Harmonised and saved.

### Social trust/cohesion

 + Harmonised variable: `trust`
 + Study: `ELSA`
 + Waves: Wave 2
 + Changes: Deleted.

 + Harmonised variable: `trust`
 + Study: `ELSA`
 + Waves: Wave 7
 + Changes: Harmonised and saved.



### Life events

 + Harmonised variable: `bereav`
 + Study: `10/66`
 + Waves: follow-up's
 + Changes: RData saved (and DataSchemas updated).

 + Harmonised variable: `bereav`
 + Study: `ELSA`
 + Waves: Wave 7
 + Changes: Harmonised and saved.

 + Harmonised variable: `bereav`
 + Study: `JSTAR`
 + Waves: all
 + Changes: corrections in the algorithms: added the study-specific variables `a_003` to waves 1 of all populations and the study-specific variable `a_013_1_a` to wave 2 of AKSST population, and labels of `a_013` changed following the questionnaire; according changes in the recodifications; missing values recodified corresponding to their meanings; missing values of children variables in waves 3 of AKSST and 2 of TN, and 'Other situations/status' categories recodified as no losses.

 + Harmonised variable: `lifethreat_sit`
 + Study: all for which the variable exists (`ELSA`,`MHAS`,`TILDA`)
 + Waves: all
 + Changes: Harmonised and saved.

 + Harmonised variable: `lifethreat_sit`,`nat_dis`,`violence`
 + Study: `ELSA`
 + Waves: 3
 + Changes: 12 IDs are removed since those individuals do not appear in the main tables of ELSA, so we do not have the essential information about them.

### Loneliness

 + Harmonised variable: `loneliness`
 + Study: `HAPIEE`
 + Waves: Lithuania - Wave 1
 + Changes: deleted, since all data was missing.


 + Harmonised variable: `loneliness`
 + Study: `HRS`,`HEALTH_2000`,`JSTAR`,`KLOSA`,`LASI`,`MHAS`,`SAGE`,`SHARE`,`TILDA`
 + Waves: all
 + Changes: Harmonised and saved.


## Other administrative variables

 + Harmonised variable: `yintw`
 + Study: `HRS`
 + Waves: all
 + Changes: correction in the algorithm: `NA` recodified as `999`.

 + Harmonised variable: `athlos_id`
 + Study: `SAGE`
 + Waves: all
 + Changes: correction: the wrong blank is changed by a zero.

 + Harmonised variable: `athlos_id`
 + Study: `TILDA`
 + Waves: all
 + Changes: correction: a distinct `athlos_id` is assigned to each individual.

 + Harmonised variable: `athlos_id2`
 + Study: all
 + Waves: all
 + Changes: Harmonised and saved. It is the same variable that `athlos_id` after removing hyphens.

 + Harmonised variable: `respondent`
 + Study: all
 + Waves: all
 + Changes: Harmonised and saved.

