---
title: "Version 1.2 beta"
output: 
  html_document:
    highlight: tango
    number_sections: no
    theme: united
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: yes
      smooth_scroll: yes

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = F)
```

NEW VERSION (1.2) OF HARMONISED DATASETS ARE READY IN OPAL 

CHANGES FROM PREVIOUS VERSION (1.1) ARE DESCRIBED BELOW.

# Changes


## Socio-demographic and economic characteristics

### Age [^1]

 + Harmonised variable: `age`
 + Study: `10/66`
 + Waves: 2
 + Changes: corrections of the harmonisation algorithm: added to age in wave 1 the difference of years between waves.

 + Harmonised variable: `age`
 + Study: `ALSA`,`MHAS`
 + Waves: all.
 + Changes: harmonisation algorithm done starting from harmonised variables on date of birth and date of interview.
 
 <!--age in each wave computed from wave 1 adding the proper differences between the years of the waves.-->

 + Harmonised variable: `age`
 + Study: `COURAGE`
 + Waves: 2
 + Changes: corrections of the harmonisation algorithm: age for each population computed suitably from date of birth, dates of interview and age in wave 1.

 + Harmonised variable: `age`
 + Study: `ELSA`
 + Waves: 2
 + Changes: corrections of the harmonisation algorithm: missing ages computed suitably from date of birth and date of interview.
 
 + Harmonised variable: `age`
 + Study: `ELSA`,`HAPIEE`,`JSTAR`
 + Waves: all
 + Changes: corrections of the harmonisation algorithm: missing ages recodified using dates of birth and interview.

 + Harmonised variable: `age`
 + Study: `ALSA`,`ATTICA`,`CHARLS`,`COURAGE`,`HAPIEE`,`JSTAR`,`HRS`
 + Waves: all.
 + Changes: corrections of the harmonisation algorithm: dead and dropout id's recodified as 996.
 
 + Harmonised variable: `age`
 + Study: `LASI`
 + Waves: pilot
 + Changes: added to harmonisation algorithm the harmonised variables `mbirth`,`ybirth` to approximate age for missing values.

### Sex/gender

 + Harmonised variable: `sex`
 + Study: `ALSA`
 + Waves: 9
 + Changes: corrections of the harmonisation algorithm: use of study-specific variable of wave 1 instead of that of wave 9 and correction of four individuals data.

 + Harmonised variable: `sex`
 + Study: `CHARLS`
 + Waves: 1
 + Changes: corrections of the harmonisation algorithm: individuals with dissenting data with wave 2 are harmonised correspondingly to wave 2 data.

### Marital Status

 + Harmonised variable: `marital_status`
 + Study: `ALSA`
 + Waves: 6,7,8,9,10
 + Changes: corrections in the algorithm: 0 or 99 recodified as 995.

 + Harmonised variable: `marital_status`
 + Study: `LASI`
 + Waves: pilot
 + Changes: used the study-specific variable `rmaritalstatus_r` instead of `rmaritalstatus_h`.

## Lifestyle and health behaviours

### Alcohol

 + Harmonised variable: `current_oh`,`freq_oh`,`past_oh`
 + Study: `ATTICA`
 + Waves: all for which possible (1).
 + Changes: Harmonised and saved.


## Health status and functional limitations

### Health metric



 + Harmonised variable: `walking_speed`,`walking_speed_c`
 + Study: `HRS`
 + Waves: all
 + Changes: Harmonised and saved.


## Diseases

 + Harmonised variable: `h_cpd_age`
 + Study: `JSTAR`
 + Waves: TN - Wave 1
 + Changes: correction of the harmonisation algorithm: missing value NA recodified as missing 999.


 + Harmonised variable: `h_angina_age`
 + Study: `COURAGE`
 + Waves: Spain - Wave 2
 + Changes: correction of the harmonisation algorithm: missing values recodified as missing.

 + Harmonised variable: `mi_ha_age`
 + Study: `SHARE`
 + Waves: 4
 + Changes: correction of the harmonisation algorithm: values 125 and 1995 recoded as 999.

 + Harmonised variable: `mi_ha_age`,`stroke_age`,`cvd`,`cvd_hard`,`cvd_all`
 + Study: `SHARE`
 + Waves: 4,5
 + Changes: correction of the harmonisation algorithm: used properly wave 5 tables instead of wave 4 ones for `mi_ha_age`,`stroke_age`. Harmonised variables `cvd`,`cvd_hard`,`cvd_all` updated.

 + Harmonised variable: `oral_problems`
 + Study: `ALSA`,`COURAGE`,`ELSA`,`HEALTH_2000`,`KLOSA`,`LASI`,`SAGE`,`SHARE`, `TILDA`
 + Waves: all
 + Changes: Harmonised and saved.


## Physical measures

 + Harmonised variable: `weight`,`height`,`bmi`,`obesity`
 + Study: `CHARLS`
 + Waves: all
 + Changes: corrections of the harmonisation algorithm of `height` and `weight`: suitable low values of `qi002` assumed to be height measured in meters or decimeters. Other low values of `qi002` and `ql002` recodified as `999`. `bmi` harmonised starting from `height` and `weight`. Update of `obesity` with previously changed data of `bmi`.

 + Harmonised variable: `height`,`bmi`,`obesity`
 + Study: `SHARE`
 + Waves: all
 + Changes: corrections of the harmonisation algorithm of `height` and `bmi`: suitable low values of `ph013_` assumed to be height measured in meters or decimeters. Update of `obesity` with previously changed data of `bmi`.

 + Harmonised variable: `waist`
 + Study: `10/66`
 + Waves: India - Wave 1
 + Changes: corrections of the harmonisation algorithm: `9999` recodified as `999`

 + Harmonised variable: `grip`
 + Study: `HRS`
 + Waves: all
 + Changes: Harmonised and saved.

 + Harmonised variable: `heart_rate`
 + Study: `10/66`,`CHARLS`,`COURAGE`,`HAPIEE`,`HEALTH_2000`,`MHAS`,`SAGE`
 + Waves: all
 + Changes: Harmonised and saved.


## Social environment

### Social participation

 + Harmonised variable: `sport`
 + Study: `JSTAR`
 + Waves: all
 + Changes: corrections in the algorithms: use of variables after which there is a skip that produced a dichotomous answer `Yes-missing` in the only variables taken into account previously.


### Loneliness


 + Harmonised variable: `loneliness`
 + Study: `10/66`
 + Waves: all
 + Changes: corrections in the algorithms: missing value 9 recodified as 996. If `Q871==0`, while `Q881` and `Q882` are zero or missing, `loneliness` codified as 0.


## Other administrative variables

 + Harmonised variable: `yintw`,`mintw`
 + Study: `ALSA`
 + Waves: 1,2,4
 + Changes: corrections of the harmonisation algorithm: added 1900 to abbreviated (e.g. 92 instead of 1992) year of interview. Moreover, the individuals harmonised in wave 2 are just those interviewed.

 + Harmonised variable: `proxy`
 + Study: `CHARLS`, `COURAGE`, `KLOSA`, `TILDA`
 + Waves: all
 + Changes: Harmonised and saved.

 + Harmonised variable: `proxy`
 + Study: `SAGE`
 + Waves: Mexico - Wave 1
 + Changes: Use of study-specific variable `q1005` instead of `q1000b`.

 + Harmonised variable: `respondent`
 + Study: `LASI`
 + Waves: pilot
 + Changes: Harmonised and saved.

 + Harmonised variable: `household_id`
 + Study: `LASI`
 + Waves: pilot
 + Changes: Harmonised and saved.

 + Harmonised variable: `household_id`
 + Study: `SAGE`
 + Waves: 1
 + Changes: Use of study-specific variable `q0002` instead of `q1006`.




[^1]: This could affect all other harmonised variables using `age` (like may be age of retirement or age of diagnostic when applicable, etc.)