---
title: "Version 1.3 beta"
output: 
  html_document:
    highlight: tango
    number_sections: no
    theme: united
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: yes
      smooth_scroll: yes

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = F)
```

NEW VERSION (1.3) OF HARMONISED DATASETS ARE READY IN OPAL 

CHANGES FROM PREVIOUS VERSION (1.2) ARE DESCRIBED BELOW.

# Changes

## Health status and functional limitations

### Health metric


 + Harmonised variable: `pain`
 + Study: `ENRICA`
 + Waves: all
 + Changes: harmonisation algorithm remade from new study-specific variable.

 + Harmonised variable: `dizziness`, `pain`,`incontinence`,`hearing_gen`,`eye_gen`,`eye_far`,`eye_near`,`iadl_housewk`
 + Study: `HRS`
 + Waves: all
 + Changes: Harmonised and saved.

 + Harmonised variable: `cog_num`, `cog_num_c`
 + Study: `JSTAR`,`SHARE`
 + Waves: all
 + Changes: harmonisation algorithm remade.




## Death

 + Harmonised variable: `living_status`
 + Study: `HEALTH_2000`
 + Waves: 2
 + Changes: In wave 2, new individuals are not removed any more. Also, they are not removed from the data of the rest of variables when the merge and the upload to OPAL are done.


## Physical measures

 + Harmonised variable: `height`,`bmi`,`obesity`
 + Study: `CHARLS`,`COURAGE`
 + Waves: all
 + Changes: corrections of `height` data of some particular individuals generating very extreme values of `height` and/or `bmi`. Update of `obesity` and `bmi` with previously changed data of `height`.

 + Harmonised variable: `weight`,`height`,`bmi`,`obesity`
 + Study: `HAPIEE`
 + Waves: Czech Republic - Wave 1
 + Changes: an id recodified as missing in `weight` and `height`. `bmi`,`obesity` updated.

 + Harmonised variable: `bmi`,`obesity`
 + Study: `MHAS`
 + Waves: all
 + Changes: recodification of some missing values.

 + Harmonised variable: `waist`
 + Study: `HAPIEE`
 + Waves: Lithuania - Wave 1
 + Changes: recodification of missing value 999.90002 into 999.

