---
title: "Version 1.4 beta"
output: 
  html_document:
    highlight: tango
    number_sections: no
    theme: united
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: yes
      smooth_scroll: yes

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = F)
```

NEW VERSION (1.4) OF HARMONISED DATASETS ARE READY IN OPAL 

CHANGES FROM PREVIOUS VERSION (1.3) ARE DESCRIBED BELOW.

# Changes

## Database

 + Study: `HRS`
 + Cohort: `AHEAD`
 + Waves: all
 + Changes: `athlos_id2=="90204982"` is drop-out for `living_status` in all waves and almost all its data is missing, so we removed it.

## Socio-demographic and economic characteristics

### Age

 + Harmonised variable: `dbirth`,`mbirth`,`ybirth`,`age`
 + Study: `COURAGE`
 + Waves: all in cohort Spain
 + Changes: correction of some original data according to information by source study researchers.

 + Harmonised variable: `ybirth`,`age`
 + Study: `SHARE`
 + Waves: all
 + Changes: correction in the harmonisation algorithms: some missing values of `yrbirth` recodified using other waves data.

 + Harmonised variable: `ybirth`,`age`
 + Study: `SAGE`
 + Waves: all
 + Changes: correction in the harmonisation algorithms: missing values of `yrbirth` imputed using `q0407` and harmonised variable `yintw`; those of `age`, using the harmonised variables for date of birth and date of interview.

 + Harmonised variable: `age`
 + Study: `ALSA`
 + Waves: all
 + Changes: correction in the harmonisation algorithm: specific days of birth and interview taken into consideration.

### Education

 + Harmonised variable: `education`
 + Study: `SHARE`
 + Waves: 2,4,5
 + Changes: correction in the harmonisation algorithm: imputed values of previous waves on individuals with missing education data.


### Residence

 + Harmonised variable: `resid_place`
 + Study: `10/66`,`ALSA`,`CHARLS`,`COURAGE`,`HRS`,`KLOSA`,`LASI`,`SAGE`,`SHARE`,`TILDA`
 + Waves: all
 + Changes: Harmonised and saved.


## Lifestyle and health behaviours

### Tobacco

 + Harmonised variable: `current_smoking`,`ever_smoked`
 + Study: `SHARE`
 + Waves: all
 + Changes: correction in the algorithm: missing values recategorized using `br001_` and `br002_` respectively (which produced skips)

 + Harmonised variable: `current_smoking`
 + Study: `10/66`,`TILDA`
 + Waves: 1
 + Changes: correction in the algorithm: missing values recategorized using variables on ever smoking (which produced skips)

 + Harmonised variable: `current_smoking`
 + Study: `Health2000`,`KLOSA`,`LASI`,`MHAS`,`SAGE`
 + Waves: all
 + Changes: correction in the algorithm: missing values recategorized using variables on ever smoking (which produced skips)

## Health status and functional limitations

### Health metric

 + Harmonised variable: `iadl_meals`,`iadl_phone`,`iadl_shopping`
 + Study: `SHARE`
 + Waves: 3
 + Changes: removed. The harmonisation done till now was from a variable about deceased people.

 + Harmonised variable: `recent_falls`, `conseq_falls`
 + Study: `HRS`
 + Waves: all
 + Changes: Harmonised and saved.

 + Harmonised variable: `trait`
 + Study: all
 + Waves: all
 + Changes: Harmonised and saved.

 + Harmonised variable: `healthstatus`
 + Study: all
 + Waves: all
 + Changes: Recalculated.


## Death

 + Harmonised variable: `living_status`
 + Study: `HRS`,`JSTAR`
 + Waves: 3 and on.
 + Changes: correction in the harmonisation algorithm: dead individuals are harmonised as dead from the first wave in which they reach this category.

 + Harmonised variable: `living_status`
 + Study: `LASI`
 + Waves: all
 + Changes: Harmonised and saved.

## Physical measures

 + Harmonised variable: `height`,`bmi`,`obesity`
 + Study: `SHARE`
 + Waves: 2,4,5
 + Changes: correction in the harmonisation algorithm: imputed values of previous waves on individuals with missing height data. `obesity` updated.

## Social environment

### Social network

 + Harmonised variable: `f_cont_fr`
 + Study: `10/66`,`ALSA`,`COURAGE`,`ELSA`,`ENRICA`,`HAPIEE`,`KLOSA`,`LASI`,`TILDA`
 + Waves: all.
 + Changes: Harmonised and saved.



 + Harmonised variable: `f_other_fr`
 + Study: `ELSA`,`LASI`
 + Waves: all.
 + Changes: Harmonised and saved.


## Other administrative variables

 + Harmonised variable: `dintw`,`mintw`
 + Study: `ALSA`
 + Waves: 7,9
 + Changes: correction in the harmonisation algorithm: recodification of missing values.

 + Harmonised variable: `proxy`
 + Study: `SHARE`
 + Waves: 3
 + Changes: Harmonised and saved.


 + Harmonised variable: `respondent`
 + Study: `CHARLS`
 + Waves: 2
 + Changes: Harmonised and saved.

 + Harmonised variable: `respondent`
 + Study: `ENRICA`
 + Waves: 3
 + Changes: correction in the harmonisation algorithm: harmonised and saved.


 + Harmonised variable: `respondent`
 + Study: `SHARE`
 + Waves: all
 + Changes: New harmonisation.
