---
title: "Version 1.5 beta"
output: 
  html_document:
    highlight: tango
    number_sections: no
    theme: united
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: yes
      smooth_scroll: yes

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = F)
```

NEW VERSION (1.5) OF HARMONISED DATASETS ARE READY IN OPAL 

CHANGES FROM PREVIOUS VERSION (1.4) ARE DESCRIBED BELOW.

# Changes


## Socio-demographic and economic characteristics

### Age

 + Harmonised variable: `ybirth`
 + Study: `CHARLS`
 + Waves: all
 + Changes: correction in the harmonisation algorithm: some missing values harmonised with data from `ba004` and `iyear`.

 + Harmonised variable: `age`
 + Study: `CHARLS`
 + Waves: 2
 + Changes: correction in the harmonisation algorithm: some missing values harmonised using `ba004`.

 + Harmonised variable: `ybirth`
 + Study: `COURAGE`
 + Waves: all
 + Changes: correction in the harmonisation algorithm: some missing values harmonised with data from `q1011_age` and `yinter`.

 + Harmonised variable: `ybirth`
 + Study: `HEALTH2000`
 + Waves: 2
 + Changes: correction in the harmonisation algorithm: wave 2 harmonised using variable `SYNTVUOSI` from wave 2 table `t11_athlos_2017_02_27`.

 + Harmonised variable: `age`
 + Study: `JSTAR`
 + Waves: all waves for `AKSST` cohort
 + Changes: correction of `age` data of seven id's whose `ybirth` data is corrected according to confirmation data provided in wave 3.

 + Harmonised variable: `ybirth`
 + Study: `LASI`
 + Waves: pilot
 + Changes: correction in the harmonisation algorithm: some missing values harmonised with data from `dm008` and year of interview.

 + Harmonised variable: `dbirth`,`mbirth`,`ybirth`,`age`
 + Study: `MHAS`
 + Waves: all.
 + Changes: date of birth of some participants who answered a new one in wave 3 confirmation is not corrected any more, due to this produced that they were not inside the eligibility sample. Variable `age` updated accordingly and using exact day information of dates of birth and interview.

 + Harmonised variable: `ybirth`,`age`
 + Study: `SAGE`
 + Waves: 1
 + Changes: correction in the harmonisation algorithms: use of variable `q1011` instead of `q0407` up to for missing values of the first one; some years of birth outside the eligibility sample recodified as missing.

## Health status and functional limitations

### Health status measure

 + Harmonised variable: `healthstatus`
 + Study: all
 + Waves: all
 + Changes: Now this variable is rescaled by study, country and wave. 

 + Harmonised variable: `trait`,`healthstatus`
 + Study: HRS
 + Cohorts: all up to `HRS`
 + Changes: Correction in the distribution of waves. Before, wave w of `AHEAD` contained `trait` and `healthstatus` data from wave w-1 (so wave 2 had only missing data). For `CODA`,`WB` cohorts, each wave w contained data from wave w-3 (so waves 4,5,6 had only missing data). Idem for the other 2 cohorts.

## Other administrative variables

 + Harmonised variable: `respondent`
 + Study: `HRS`
 + Waves: all
 + Changes: New harmonisation.
