---
title: "Version 1.6 beta"
output: 
  html_document:
    highlight: tango
    number_sections: no
    theme: united
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: yes
      smooth_scroll: yes

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = F)
```

NEW VERSION (1.6) OF HARMONISED DATASETS ARE READY IN OPAL 

CHANGES FROM PREVIOUS VERSION (1.5) ARE DESCRIBED BELOW.

# Changes

## Database

 + Harmonised variable: 
 + Study: `ELSA`
 + Waves: 3
 + Changes: all id's which do not appear in the main table of ELSA in wave 3 are removed (even those which appear through other waves), since we do not have the essential information about them. (these id's only appear in a table used for the harmonisation of `bereav`,`lifethreat_sit`,`nat_dis`, and `violence`). 


## Socio-demographic and economic characteristics


### Sex/gender

 + Harmonised variable: `sex`
 + Study: `TILDA`
 + Waves: all
 + Changes: corrections of the harmonisation algorithm: the codification of females and males was wrong (inverted); solved.


### Labour force and retirement


 + Harmonised variable: `age_retired`
 + Study: `10/66`
 + Waves: 2
 + Changes: Updated after changes in variable `age` in version 1.2 of harmonised dataset.

 + Harmonised variable: `age_retired`
 + Study: `ENRICA`
 + Waves: 2 to 3
 + Changes: Floor function was applied to approximate age.

### Citizenship and immigration status

 + Harmonised variable: `migration`,`ymigration`
 + Study: all
 + Waves: all
 + Changes: Harmonised and saved.



## Lifestyle and health behaviours

### Physical activity

 + Harmonised variable: `f_vig_pa`
 + Study: `HEALTH_2000`
 + Waves: 1
 + Changes: Harmonised and saved.

 + Harmonised variable: `t_vig_pa`
 + Study: `HEALTH_2000`
 + Waves: all
 + Changes: correction in the harmonisation algorithm: introduction of variables `KYS1_K30T`, `KYS1_K29` and `T11_KYS1_K24_4T` to harmonise complete time in a week.


## Health status and functional limitations

### Health metric


 + Harmonised variable: `orientation`,`eye_far`,`eye_near`
 + Study: `HEALTH_2000`
 + Waves: all
 + Changes: Harmonised and saved.

 + Harmonised variable: `energy`
 + Study: `HEALTH_2000`
 + Waves: 1
 + Changes: Harmonised and saved.

 + Harmonised variable: `energy`
 + Study: `HEALTH_2000`
 + Waves: 2
 + Changes: Use of study-specific variable `KYS3_ENER` instead of `T11_KYS1_K43_1`.


## Diseases


 + Harmonised variable: `h_diabetes_age`,`h_asthma_age`,`h_hypertension_age`,`h_joint_disorders_age`,`h_angina_age`,`mi_ha_age`,`stroke_age`
 + Study: `10/66`
 + Waves: 2
 + Changes: Updated after changes in variable `age` in version 1.2 of harmonised dataset.

 + Harmonised variable: `h_diabetes_age`,`h_asthma_age`,`h_cpd_age`,`h_hypertension_age`,`h_joint_disorders_age`,`h_angina_age`
 + Study: `ALSA`
 + Waves: 12
 + Changes: Updated after changes in variable `age` in version 1.4 of harmonised dataset.

 + Harmonised variable: `h_joint_disorders_age`
 + Study: `ALSA`
 + Waves: 7
 + Changes: Updated after changes in variable `age` in version 1.4 of harmonised dataset.

 + Harmonised variable: `h_diabetes_age`,`h_cpd_age`,`h_hypertension_age`,`h_joint_disorders_age`,`stroke_age`
 + Study: `CHARLS`
 + Waves: all.
 + Changes: Updated after changes in variables `ybirth` and `age` in version 1.5 of harmonised dataset.

 + Harmonised variable: `h_respiratory`
 + Study: `CHARLS`
 + Waves: 2
 + Changes: correction in the harmonisation algorithm: as for `h_asthma` and `h_cpd`, id's with missing values in study-specific variables but diagnosis age or year are harmonised as having chronic respiratory diseases.

 + Harmonised variable: `h_diabetes_age`,`h_asthma_age`,`h_hypertension_age`,`h_joint_disorders_age`,`h_angina_age`,`stroke_age`
 + Study: `COURAGE`
 + Waves: 2
 + Changes: Updated after changes in variable `age` in version 1.4 of harmonised dataset. A small change in harmonisation was done too (`floor(approximated age)`).

 + Harmonised variable: `h_cpd_age`
 + Study: `COURAGE`
 + Waves: 2
 + Changes: Updated after changes in variable `age` in version 1.4 of harmonised dataset.

 + Harmonised variable: `h_asthma_age`,`h_cpd_age`,`h_hypertension_age`
 + Study: `ELSA`
 + Waves: 2 to 6
 + Changes: Floor function was applied to approximate age.

 + Harmonised variable: `h_asthma_age`,`h_cpd_age`,`h_hypertension_age`
 + Study: `ELSA`
 + Waves: 7
 + Changes: Harmonised and saved.

 + Harmonised variable: `mi_ha_age`,`stroke_age`
 + Study: `ELSA`
 + Waves: 2
 + Changes: Updated after changes in variable `ybirth` in version 1.2 of harmonised dataset.

 + Harmonised variable: `h_diabetes_age`,`h_hypertension_age`,`mi_ha_age`,`stroke_age`,`cancer_age`
 + Study: `ENRICA`
 + Waves: 2 to 3
 + Changes: Floor function was applied to approximate age.

## Death

 + Harmonised variable: `living_status`,`ydeath`
 + Study: `ELSA`
 + Waves: 2 and on.
 + Changes: new harmonisation.


## Other administrative variables


 + Harmonised variable: `proxy`
 + Study: `ELSA`
 + Waves: 5
 + Changes: correction of harmonisation algorithm after changing table from which getting the study-specific variable: wave 5 proxy data got rightly (previously, harmonised data was wrongly from wave 4)
