---
title: "Version 1.7 beta"
output: 
  html_document:
    highlight: tango
    number_sections: no
    theme: united
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: yes
      smooth_scroll: yes

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = F)
```

NEW VERSION (1.7) OF HARMONISED DATASETS ARE READY IN OPAL 

CHANGES FROM PREVIOUS VERSION (1.6) ARE DESCRIBED BELOW.

## Socio-demographic and economic characteristics

### Labour force and retirement


 + Harmonised variable: `age_retired`
 + Study: `MHAS`
 + Changes: Updated after changes in variable `ybirth` in versions 1.1 and 1.5 of harmonised dataset.

 + Harmonised variable: `age_retired`
 + Study: `SHARE`
 + Waves: 4
 + Changes: Updated after changes in variable `ybirth` in version 1.4 of harmonised dataset.


## Lifestyle and health behaviours

### Alcohol


 + Harmonised variable: `past_oh`
 + Study: `HAPIEE`
 + Changes: correction of harmonisation algorithm: recodification of some missing values as `996 (Not applicable)` instead of `999 (Missing)`

### Physical activity

 + Harmonised variable: `t_walks`
 + Study: `HEALTH2000`
 + Changes: Harmonised and saved.

## Health status and functional limitations

### Health metric


 + Harmonised variable: `adl_toilet`
 + Study: `ALSA`
 + Waves: 1,2,5
 + Changes: correction of harmonisation algorithm: use of study-specific variables `ACTIV5` and `ADLND5W5` instead of variables `DIFFIC5` and `ADLHP5W5` in waves 1 and 5 respectively; added variable `Q34` to wave 2.

 + Harmonised variable: `adl_bathing`
 + Study: `ALSA`
 + Waves: 2,5
 + Changes: correction of harmonisation algorithm: use of study-specific variable `ADLND1W5` instead of variable `ADLHP1W5` in wave 5; added variable `Q34` to wave 2.

 + Harmonised variable: `adl_bed`
 + Study: `ALSA`
 + Waves: 1,2
 + Changes: correction of harmonisation algorithm: use of study-specific variable `ACTIV8` instead of wrong variable `ACTIV1` (wave 1); added variable `Q34` (wave 2)
 
 + Harmonised variable: `adl_dressing`
 + Study: `ALSA`
 + Waves: 2
 + Changes: correction of harmonisation algorithm: added variable `Q34`.


 + Harmonised variable: `adl_eating`,`adl_moving`
 + Study: `ALSA`
 + Waves: 1,2
 + Changes: correction of harmonisation algorithm: use of study-specific variables `ACTIV5` and `ACTIV7` instead of variables `DIFFIC5` and `DIFFIC7` respectively in wave 1; added variable `Q34` to wave 2.

 + Harmonised variable: `cog_imm`, `cog_imm_c`
 + Study: `HRS`
 + Cohorts: `HRS`
 + Waves: 9,10
 + Changes: correction of harmonisation algorithm: imputed values preserved.

 + Harmonised variable: `cog_imm`, `cog_imm_c`
 + Study: `LASI`
 + Changes: recodification of a missing value as `991`.

 + Harmonised variable: `cog_imm`, `cog_imm_c`,`cog_del`, `cog_del_c`
 + Study: `JSTAR`
 + Changes: correction of harmonisation algorithm: recodification of missing values as other missing types or zero.

 + Harmonised variable: `cog_imm`, `cog_imm_c`,`cog_del`,`cog_del_c`
 + Study: `TILDA`
 + Wave: 1
 + Changes: correction of harmonisation algorithm: use of original variables `ph116`,`ph117`,`ph119`,`ph712` and `ph713` instead of derived variables `COGimmediaterecall1` and `COGdelayedrecall`; recodification of some missing values as 0.

 + Harmonised variable: `cog_imm`, `cog_imm_c`,`cog_verb`, `cog_verb_c`,`cog_del`, `cog_del_c`, `cog_num`, `cog_num_c`
 + Study: `HEALTH2000`
 + Changes: Harmonised and saved.
 
 + Harmonised variable: `cog_num`, `cog_num_c`
 + Study: `ENRICA`
 + Waves: 3
 + Changes: Harmonised and saved.

 + Harmonised variable: `evaluative_wb`
 + Changes: Harmonised and saved.


 + Harmonised variable: `trait`
 + Study: all
 + Waves: all
 + Changes: Recalculated.

 + Harmonised variable: `healthstatus`
 + Study: all
 + Waves: all
 + Changes: Recalculated.

## Diseases


 + Harmonised variable: `h_diabetes_age`,`h_cpd_age`,`h_hypertension_age`
 + Study: `HAPIEE`
 + Cohorts: `Poland`, `Czech Republic`
 + Waves: 2
 + Changes: Floor function was applied to approximate age.


 + Harmonised variable: `cancer_age`,`h_hypertension_age`,`h_angina_age`
 + Study: `HEALTH2000`
 + Waves: 2
 + Changes: Floor function was applied to approximate age.

 + Harmonised variable: `h_cpd_age`
 + Study: `HEALTH2000`
 + Waves: 2
 + Changes: correction of harmonisation algorithm: computed approximated age for new diagnosis between waves.

 + Harmonised variable: `h_diabetes_age`,`mi_ha_age`
 + Study: `HEALTH2000`
 + Waves: 2
 + Changes: Updated after changes in variable `ybirth` in version 1.5 of harmonised dataset.

 + Harmonised variable: `h_asthma_age`,`h_joint_disorders_age`
 + Study: `HEALTH2000`
 + Waves: 2
 + Changes: Updated after changes in variable `ybirth` in version 1.5 of harmonised dataset; missing values `NA` recoded as `999`.

 + Harmonised variable: `cancer_age`,`h_diabetes_age`,`h_hypertension_age`,`h_joint_disorders_age`,`stroke_age`
 + Study: `HRS`
 + Waves: all except first of each cohort
 + Changes: Updated after changes in variable `yintw` and `mintw` in version 1.1 of harmonised dataset (it has only affected to `cancer_age` and `stroke_age`); further, floor function was applied to approximate age.

 + Harmonised variable: `h_cpd_age`
 + Study: `HRS`
 + Waves: all except first of each cohort
 + Changes: Floor function was applied to approximate age.


 + Harmonised variable: `h_joint_disorders_age`
 + Study: `KLOSA`
 + Waves: 3,4
 + Changes: correction of harmonisation algorithm: `ybirth` taken into account for newly diagnosed in wave 3.

 + Harmonised variable: `cancer_age`,`mi_ha_age`,`stroke_age`
 + Study: `MHAS`
 + Changes: Updated after changes in variable `ybirth` in versions 1.1 and 1.5 of harmonised dataset.

 + Harmonised variable: `h_diabetes_age`,`h_hypertension_age`,`h_joint_disorders_age`
 + Study: `MHAS`
 + Waves: 2,3
 + Changes: Updated after changes in variables `ybirth` and `age` in versions 1.1, 1.2 and 1.5 of harmonised dataset; floor function was applied to approximate age.

## Death

 + Harmonised variable: `living_status`,`ydeath`
 + Study: `ELSA`
 + Waves: 2 and on.
 + Changes: new harmonisation. More deaths identified from study-specific variables not previously found.

 + Harmonised variable: `living_status`
 + Study: `COURAGE`
 + Cohorts: `Spain`
 + Waves: 2
 + Changes: correction of harmonisation algorithm: use of original variable `q0007_updated` instead of `q0006_date_s1`.

 + Harmonised variable: `suicidal_ideation_12m`, `suicidal_ideation_lm`
 + Changes: Harmonised and saved.

## Physical measures

 + Harmonised variable: `grip`
 + Study: `HRS`
 + Changes: recodification of missing values using variables from original stata files.

## Psychological measures

 + Harmonised variable: `dementia`, `dementia_age`
 + Changes: Harmonised and saved.


## Social environment

### Social network

 + Harmonised variable: `child`
 + Study: `HEALTH2000`
 + Changes: Harmonised and saved.


### Social participation

 + Harmonised variable: `pol_act`
 + Study: `SAGE`
 + Changes: Harmonised and saved.


 + Harmonised variable: `pol_act`,`relig`
 + Study: `JSTAR`
 + Changes: correction of the harmonisation algorithm: use of filter variables, introducing negative data.


 + Harmonised variable: `part_clubs`
 + Study: `HEALTH2000`
 + Changes: Harmonised and saved.

## Other administrative variables

 + Harmonised variable: `w`
 + Study: `HEALTH2000`
 + Changes: Harmonised and saved.
