---
title: "Version 2.0"
output: 
  html_document:
    highlight: tango
    number_sections: no
    theme: united
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: yes
      smooth_scroll: yes

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = F)
```

NEW VERSION (2.0) OF HARMONISED DATASETS ARE READY IN OPAL 

CHANGES FROM PREVIOUS VERSION (1.7) ARE DESCRIBED BELOW.


## Socio-demographic and economic characteristics

### Education

 + Harmonised variable: `education`
 + Study: `ALSA`
 + Waves: 1
 + Changes: Harmonised and saved.

 + Harmonised variable: `parentedu`
 + Changes: Harmonised and saved.

### Wealth

 + Harmonised variable: `childsep`
 + Changes: Harmonised and saved.



## Health status and functional limitations

### Health metric

 + Harmonised variable: `walking_speed`, `walking_speed_c`
 + Study: `TILDA`
 + Wave: 1
 + Changes: Harmonised and saved.

 + Harmonised variable: `mob_sit`, `mob_climb`, `mob_stoop`, `mob_arm`, `mob_pull`, `mob_lift`, `mob_coin`
 + Study: `TILDA`
 + Changes: Harmonised and saved.

 + Harmonised variable: `mob_up`
 + Study: `TILDA`
 + Changes: new harmonisation using study-specific variable `fl001_04` instead of `ph413`

 + Harmonised variable: `adl_toilet`
 + Study: `TILDA`
 + Changes: new harmonisation using study-specific variable `fl002_6` instead of `fl019`

 + Harmonised variable: `adl_bathing`
 + Study: `TILDA`
 + Changes: new harmonisation using study-specific variable `fl002_3` instead of `fl011`

 + Harmonised variable: `adl_dressing`
 + Study: `TILDA`
 + Changes: new harmonisation using study-specific variable `fl002_1` instead of `fl005`

 + Harmonised variable: `adl_eating`
 + Study: `TILDA`
 + Changes: new harmonisation using study-specific variable `fl002_4` instead of `fl013`

 + Harmonised variable: `adl_bed`
 + Study: `TILDA`
 + Changes: new harmonisation using study-specific variable `fl002_5` instead of `fl016`

 + Harmonised variable: `adl_moving`
 + Study: `TILDA`
 + Changes: correction of harmonisation algorithm: added variable `DISimpairments`, so `Not applicable` values are recoded as `1`.

 + Harmonised variable: `trait`, `healthstatus`
 + Changes: Updated after adding to building process last corrections and harmonisations of health metric variables.
 
 


## Diseases


 + Harmonised variable: `multimorbid`
 + Changes: Harmonised and saved.




## Death

 + Harmonised variable: `living_status`
 + Study: `HRS`
 + Waves: 2 and on.
 + Changes: correction of harmonisation algorithm: use of variables on date of death and date of interview to harmonise dead `Dropout`'s as `Dead`. Fixed harmonisation of wave 9 of cohort `EBB` (there was a wrong reference to cohort `WB`)





## Social environment


### Social participation

 + Harmonised variable: `sen_club`
 + Study: `ALSA`
 + Waves: 3
 + Changes: correction of harmonisation algorithm. Missing values become `No` participation in senior clubs.


