---
title: "Version 2.1"
output: 
  html_document:
    highlight: tango
    number_sections: no
    theme: united
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: yes
      smooth_scroll: yes

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = F)
```

NEW VERSION (2.1) OF HARMONISED DATASETS ARE READY IN OPAL 

CHANGES FROM PREVIOUS VERSION (2.0) ARE DESCRIBED BELOW.



## Socio-demographic and economic characteristics


 + Harmonised variable: `sex`
 + Study: `ELSA`
 + Waves: 2,7
 + Changes: sex of 2 individuals distinct through waves in study-specific variables is homogenized.





## Health status and functional limitations

### Health metric

 + Harmonised variable: `walking_speed`, `walking_speed_c`
 + Study: `10/66`
 + Changes: Harmonised and saved.

### Outside health metric

 + Harmonised variable: `eudaimonic_wb`
 + Study: all (possible)
 + Wave: all (possible)
 + Changes: Harmonised and saved.




## Death

 + Harmonised variable: `living_status`
 + Study: `ALSA`
 + Waves: 3
 + Changes: individuals without interview date and dead between 01/03/1995 (end of ALSA wave 3) and 19/12/1995 are harmonised as dropout instead of dead.

 + Harmonised variable: `living_status`
 + Study: `ALSA`
 + Waves: 4
 + Changes: 3 individuals with wrong dates of interview are harmonised as alive instead of dead.

 + Harmonised variable: `living_status`
 + Study: `ALSA`
 + Waves: 5
 + Changes: correction in reading of date interviews changes the `living_status` of many individuals.

 + Harmonised variable: `living_status`
 + Study: `ALSA`
 + Waves: 5 and on
 + Changes: id 501 is considered to be alive on wave 10 and dropout otherwise, instead of dead.



## Social environment


### Social participation

 + Harmonised variable: `sen_club`,`volun`,`part_clubs`
 + Study: `JSTAR`
 + Changes: correction of the harmonisation algorithm: use of filter variables, introducing negative data.



## Other administrative variables

 + Harmonised variable: `respondent`
 + Study: `ALSA`
 + Waves: all up to 1.
 + Changes: now harmonisation is done for the correct individuals in each wave.
