---
title: "Version 2.2"
output: 
  html_document:
    highlight: tango
    number_sections: no
    theme: united
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: yes
      smooth_scroll: yes

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = F)
```

NEW VERSION (2.2) OF HARMONISED DATASETS ARE READY IN OPAL 

CHANGES FROM PREVIOUS VERSION (2.1) ARE DESCRIBED BELOW.



## Socio-demographic and economic characteristics


 + Harmonised variable: `ybirth`, `age`
 + Study: `JSTAR`
 + Cohorts: `aksst`
 + Waves: 1,2
 + Changes: Fix two id's data taking into account wave 2 correction (`k_001_1` and `k_001_3_b`)


 + Harmonised variable: `ybirth`, `age`
 + Study: `KLOSA`
 + Waves: 1,2,3
 + Changes: Fix a collection of id's data taking into account year of birth correction from other waves (mainly third and fourth)

 + Harmonised variable: `age`
 + Study: `ALSA`
 + Waves: 3
 + Changes: Update (after `yintw` correction) of an id data


 + Harmonised variable: `age`
 + Study: `COURAGE`
 + Waves: 1
 + Changes: harmonize using the difference between source variables date of interview (`q0006_date`) and date of birth (`q1010_birth_date`), and only when it is missing, the source variable for age (`q1011_age`)


 + Harmonised variable: `age`
 + Study: `ELSA`
 + Changes: Fix 4 specific id ages in specific waves taking into account birth and interview dates



 + Harmonised variable: `childsep`
 + Study: `HAPIEE`
 + Cohort: Poland
 + Waves: 2
 + Changes: fix harmonisation algorithm: categories `4 =  Clerical support workers`,`5 = Service and sales workers` are harmonised as `1 = Medium SES`.



## Lifestyle and health behaviours


 + Harmonised variables: `f_mod_pa`, `f_vig_pa`
 + Study: `HRS`
 + Cohort: all
 + Waves: all except wave 1 of `HRS` cohort
 + Changes: fix harmonisation algorithm: category `1 =  every day` is harmonised as `4 = 6-7 days per week (very often)`.



## Other administrative variables

 + Harmonised variable: `yintw`
 + Study: `ALSA`
 + Waves: 3
 + Changes: Correction of an id data