---
title: "Respondent"
output:
  html_document:
    highlight: tango
    number_sections: yes
    theme: united
    toc: yes
    toc_depth: 6
    toc_float:
      collapsed: yes
      smooth_scroll: yes
---

<!-- ########################################################## --> 
<!-- # Installation, loading packages -->
```{r setup, include=FALSE}
source("../../setup.r")
```
<!-- ########################################################## --> 
<!-- # Loading DS description -->
```{r main, child='../../_DS_Rmd/respondentDS.Rmd'}
```
```{r global, echo=F}
source('../../_DS_Rmd/respondentDS.R')
```




# Data process

## Ireland

```{r assign, echo=F}

opal.assign.table.tibble(o, 'TILDA_w1','TILDA.TILDA-AMF-v16', variables=list('cs017'), missings = TRUE)
TILDA_w1 <- opal.execute(o,'TILDA_w1')

opal.assign.table.tibble(o, 'TILDA_w2','TILDA.TILDA-AMF-v23', variables=list('bh101'), missings = TRUE)
TILDA_w2 <- opal.execute(o,'TILDA_w2')

```

#### Harmonisation algorithm

All the interviewed individuals are considered as participants. 

**R script:**

```{r harmo w1}

rm(list=setdiff(ls(), c("o","datafolder","TILDA_w1","TILDA_w2","ds_label","cat_label") )) 

dflist <- lapply(Filter(function(x) is.data.frame(get(x)), ls()), get)



ind <- 0
for(df in dflist){
  ind <- ind + 1
  respondent <- tibble(id=df$id)
  respondent$respondent <- 0
  respondent$respondent <- labelled(respondent$respondent, labels = cat_label)
  label(respondent$respondent) <- ds_label
  save(respondent,file = paste0("../RData/w",as.character(ind),"/respondent.RData"))
}

```






# Quality estimation

All respondents are participants.

<!-- ########################################################## -->
<!--- # Close OPAL R Session -->
```{r closeRsession, echo=FALSE}
opal.logout(o)
```
