---
title: "Household ID"
output:
  html_document:
    highlight: tango
    number_sections: yes
    theme: united
    toc: yes
    toc_depth: 6
    toc_float:
      collapsed: yes
      smooth_scroll: yes
---

<!-- ########################################################## --> 
<!-- # Installation, loading packages -->
```{r setup, include=FALSE}
source("../../setup_iago.r")
```
<!-- ########################################################## --> 
<!-- # Loading DS description -->
```{r main, child='../../_DS_Rmd/household_idDS.Rmd'}
```
```{r global, echo=F}
source('../../_DS_Rmd/household_idDS.R')
```



# Data process



## Ireland


### Wave 1


#### Study-specific variable description



| **Name** | `household`|
|-|-|
| **Label** | `Household Identifier`|
| **Table name**  | `TILDA-AMF-v16`|
| **Categories** | `text`|

```{r assign w1, echo=F}

opal.assign.table.tibble(o, 'TILDA_w1','TILDA.TILDA-AMF-v16',variables=list('household'), missings = T)
TILDA_w1 <- opal.execute(o,'TILDA_w1')

```


#### Harmonisation algorithm


**R script:**

```{r harmo w1}

# Categorical variable harmonization
TILDA_ds_w1 <- tibble(id=TILDA_w1$id)
TILDA_ds_w1$household_id <-as.character(TILDA_w1$household)

```




### Wave 2


#### Study-specific variable description



| **Name** | `household`|
|-|-|
| **Label** | `Household ID`|
| **Table name**  | `TILDA-AMF-v23`|
| **Categories** |  `text` |

```{r assign w2, echo=F}

opal.assign.table.tibble(o, 'TILDA_w2','TILDA.TILDA-AMF-v23',variables=list('household'), missings = T)
TILDA_w2 <- opal.execute(o,'TILDA_w2')

```



#### Harmonisation algorithm



**R script:**

```{r harmo w2}


# Categorical variable harmonization
TILDA_ds_w2 <- tibble(id=TILDA_w2$id)
TILDA_ds_w2$household_id <- as.character(TILDA_w2$household)

```







<!-- ########################################################## --> 
<!-- # Save -->
```{r save, include=FALSE, echo=F}

label(TILDA_ds_w1$household_id) <- ds_label
label(TILDA_ds_w2$household_id) <- ds_label

l.TILDA <- list(w1 = TILDA_ds_w1, w2 = TILDA_ds_w2)

for(index in seq_along(l.TILDA)){
  household_id <- l.TILDA[[index]]
  save(household_id, file = paste0(datafolder,names(l.TILDA)[index],"/household_id.RData"))
}

```
<!-- ########################################################## --> 






<!-- ########################################################## -->
<!--- # Close OPAL R Session -->
```{r closeRsession, echo=FALSE}
opal.logout(o)
```





