# Description of DataSchema variable

The description of harmonised variables is the following:

* Short name: `current_oh`
* Variable label: `Current alcohol drinker`
* Variable description: `Current alcohol drinker`
* Domain: `Lifestyle and health behaviours`
* Value type: `categorical`
* Category coding:

**Code** | **Category Label**
-------- | ------------------
0        | No
1        | Yes

* Category missings: 

**Code** | **Category Label**
----| ------------------
991 | CAPI/interviewer error
992 | Impute
993 | Disable to measure
994 | Not attempt/not done
995 | Does not answer
996 | Not applicable
997 | Refuse
998 | Do not know
999 | Missing




* Short name: `freq_oh`
* Variable label: `Frequency of alcohol drinking`
* Variable description: `Frequency of alcohol drinking`
* Domain: `Lifestyle and health behaviours`
* Value type: `categorical`
* Category coding:

**Code** | **Category Label**
-------- | ------------------
0        | never
1        | rare
2        | often

* Category missings: 

**Code** | **Category Label**
----| ------------------
991 | CAPI/interviewer error
992 | Impute
993 | Disable to measure
994 | Not attempt/not done
995 | Does not answer
996 | Not applicable
997 | Refuse
998 | Do not know
999 | Missing



* Short name: `past_oh`
* Variable label: `Past drinking`
* Variable description: `Did you drink in the past?`
* Domain: `Lifestyle and health behaviours`
* Value type: `categorical`
* Category coding:

**Code** | **Category Label**
-------- | ------------------
0        | No
1        | Yes

* Category missings: 

**Code** | **Category Label**
----| ------------------
991 | CAPI/interviewer error
992 | Impute
993 | Disable to measure
994 | Not attempt/not done
995 | Does not answer
996 | Not applicable
997 | Refuse
998 | Do not know
999 | Missing
