# Description of DataSchema variable

The description of harmonised variable is the following:

* Short name: `anxiety_symp`
* Variable label: `Psychological measure of anxiety symptoms`
* Variable description: `In this variable we will collect any anxiety symptom taking individual questions about worry, trembling, anxiety distress or severity, anxiety in general, other body features or scale items that correspond to these anxiety symptoms. In this sense, here we include a broad definition of anxiety symptoms. On a different variable we will have a more strict definition that will collect "anxiety diagnosis" following consensus criteria of studies or scale manuals. However, only 5 studies include validated scales as such and most of them are different and some of them do not mention cut-off points, are ambiguous about them, or have different criteria depending on their population.`
* Domain: `Psychological measures`
* Value type: `categorical`
* Category coding:

**Code** | **Category Label**
-------- | ------------------
0        | no anxiety symptoms
1        | presence of anxiety symptoms

* Category missings: 

**Code** | **Category Label**
----| ------------------
991 | CAPI/interviewer error
992 | Impute
993 | Disable to measure
994 | Not attempt/not done
995 | Does not answer
996 | Not applicable
997 | Refuse
998 | Do not know
999 | Missing


