# Description of DataSchema variable

The description of harmonised variable is the following:

* Short name: `cancer`
* Variable label: `Any malignancy (C00-D48) / information about past or current neoplasm (benign, in situ, malignant)`
* Variable description: `Cancer diagnosis since the last interview`
* Domain: `Diseases`
* Value type: `categorical`
* Category coding:

**Code** | **Category Label**
-------- | ------------------
0        | no cancer
1        | cancer

* Category missings: 

**Code** | **Category Label**
----| ------------------
991 | CAPI/interviewer error
992 | Impute
993 | Disable to measure
994 | Not attempt/not done
995 | Does not answer
996 | Not applicable
997 | Refuse
998 | Do not know
999 | Missing

* Short name: `cancer_age`
* Variable label: `Age of the last cancer diagnosis`
* Variable description: `Age of each episode of cancer`
* Domain: `Diseases`
* Value type: `Continuous`
* Category missings: 

**Code** | **Category Label**
----| ------------------
991 | CAPI/interviewer error
992 | Impute
993 | Disable to measure
994 | Not attempt/not done
995 | Does not answer
996 | Not applicable
997 | Refuse
998 | Do not know
999 | Missing
