# Description of DataSchema variable

The description of harmonised variable is the following:


* Short name: `cog_num`
* Variable label: `Cognition - numeracy test`
* Variable description: `Test composed by several numeracy questions. Variable dichotomised by first quartil with value 0 and higher with value 1. Presence of difficulties on numeracy questions (everyday maths problems)`
* Domain: `Health status and functional limitations`
* Value type: `categorical`
* Category coding:

**Code** | **Category Label**
-------- | ------------------
0        | <=25%
1        | >25%

* Category missings: 

**Code** | **Category Label**
----| ------------------
991 | CAPI/interviewer error
992 | Impute
993 | Disable to measure
994 | Not attempt/not done
995 | Does not answer
996 | Not applicable
997 | Refuse
998 | Do not know
999 | Missing



* Short name: `cog_num_c`
* Variable label: `Cognition - numeracy test. Continuous variable`
* Variable description: `It is assessed by means of a numeracy test composed by several numeracy questions. Presence of difficulties on numeracy questions (everyday maths problems)`
* Domain: `Health status and functional limitations`
* Value type: `continuous`
* Category missings: 


**Code** | **Category Label**
----| ------------------
991 | CAPI/interviewer error
992 | Impute
993 | Disable to measure
994 | Not attempt/not done
995 | Does not answer
996 | Not applicable
997 | Refuse
998 | Do not know
999 | Missing