# Description of DataSchema variable

The description of harmonised variable is the following:

* Short name: `h_joint_disorders`
* Variable label: `History of arthritis, rheumatism or osteoarthritis`
* Variable description: `history of arthritis, rheumatism or osteoarthritis`
* Domain: `Diseases`
* Value type: `categorical`
* Category coding:

**Code** | **Category Label**
-------- | ------------------
0        | NOT joint_disorders 
1        | joint_disorders

* Category missings: 

**Code** | **Category Label**
----| ------------------
991 | CAPI/interviewer error
992 | Impute
993 | Disable to measure
994 | Not attempt/not done
995 | Does not answer
996 | Not applicable
997 | Refuse
998 | Do not know
999 | Missing

* Short name: `h_joint_disorders_age`
* Variable label: `Age first diagnosed joint disorder`
* Variable description: `The age first told had joint disorder diagnosis`
* Domain: `Diseases`
* Value type: `Continuous`
* Category missings: 

**Code** | **Category Label**
----| ------------------
991 | CAPI/interviewer error
992 | Impute
993 | Disable to measure
994 | Not attempt/not done
995 | Does not answer
996 | Not applicable
997 | Refuse
998 | Do not know
999 | Missing
