# Description of DataSchema variable

The description of harmonised variable is the following:

* Short name: `multimorbid`
* Variable label: `Multimorbidity status`
* Variable description: 
    + `Since many of the datasets in ATHLOS do not have information about disease severity, we opted for a simple disease count as a measure of multimorbidity. This is the most common multimorbidity operational definition/measure (Huntley et al, 2012).`
    + `We used the harmonised disease variables in ATHLOS harmonised datasets. These included: diabetes, asthma, chronic pulmonary disease, hypertension, arthritis, angina, myocardial infarction and stroke. Each disease was coded as a dichotomous variable where yes (presence) = 1 and no (absence) = 0.`
    + `Multimorbid_score is the sum of all scores given to the diseases. If multimorbid_score > = 2, then the respondent is deemed to have multimorbidity, and their multimorbid_status is coded 1. Otherwise, if multimorbid_score < 2, then the respondent is deemed to not have multimorbidity and their multimorbid_status is coded 0.`
* Domain: `Diseases`
* Value type: `categorical`
* Category coding:

**Code** | **Category Label**
-------- | ------------------
0        | No
1        | Yes

* Category missings: 

**Code** | **Category Label**
----| ------------------
991 | CAPI/interviewer error
992 | Impute
993 | Disable to measure
994 | Not attempt/not done
995 | Does not answer
996 | Not applicable
997 | Refuse
998 | Do not know
999 | Missing
