# Description of DataSchema variable

The description of harmonised variable is the following:

* Short name: `obesity`
* Variable label: `Presence of obesity based in Body Mass Index classification according to the WHO BMI classification (http://apps.who.int/bmi/index.jsp?introPage=intro_3.html): BMI value equal to or above 30Kg/m^2`
* Variable description: `The BMI variable was created by dividing weight and height variables by means of the following equation: weight (kg)/height(m)^2. Then, the Obesity variable is generated according to the WHO cutoff point for BMI classification`
* Domain: `Physical measures`
* Value type: `Categorical`
* Category coding:

**Code** | **Category Label**
-------- | ------------------
0        | not obese
1        | obese

* Category missings: 

**Code** | **Category Label**
----| ------------------
991 | CAPI/interviewer error
992 | Impute
993 | Disable to measure
994 | Not attempt/not done
995 | Does not answer
996 | Not applicable
997 | Refuse
998 | Do not know
999 | Missing