# Description of DataSchema variable

The description of harmonised variable is the following:

* Short name: `oral_problems`
* Variable label: `The participant lost all the natural teeth or uses dentures (we assume that if they wear dentures it is because they have lost the teeth)`
* Variable description: `There is different information about 'oral health' ('dental visits', 'using dentures or lost natural teeth' and 'eating problems') through the multiple studies taken into account. We have harmonised 'lose natural teeth - using dentures' and we have considered 'using dentures' as a consequence of losing all the natural teeth.`
* Domain: `Diseases`
* Value type: `categorical`
* Category coding:

**Code** | **Category Label**
-------- | ------------------
0        | No
1        | Yes

* Category missings: 

**Code** | **Category Label**
----| ------------------
991 | CAPI/interviewer error
992 | Impute
993 | Disable to measure
994 | Not attempt/not done
995 | Does not answer
996 | Not applicable
997 | Refuse
998 | Do not know
999 | Missing
