# Description of DataSchema variable

The description of harmonised variable is the following:

* Short name: `cog_del`
* Variable label: `Cognition - delayed recall`
* Variable description: `Test that assesses delayed recall using the common nouns from the list previously employed for measuring Immediate recall. Variable dichotomised by first quartil with value 0 and higher with value 1.`
* Domain: `Health status and functional limitations`
* Value type: `categorical`
* Category coding:

**Code** | **Category Label**
-------- | ------------------
0        | <=25%
1        | >25%

* Category missings: 

**Code** | **Category Label**
----| ------------------
991 | CAPI/interviewer error
992 | Impute
993 | Disable to measure
994 | Not attempt/not done
995 | Does not answer
996 | Not applicable
997 | Refuse
998 | Do not know
999 | Missing





* Short name: `cog_del_c`
* Variable label: `Cognition - delayed recall. Continuous variable.`
* Variable description: `Test that assesses delayed recall using the common nouns from the list previously employed for measuring Immediate recall. The total number of words correctly recalled after a delay.`
* Domain: `Health status and functional limitations`
* Value type: `continuous`
* Category missings: 


**Code** | **Category Label**
----| ------------------
991 | CAPI/interviewer error
992 | Impute
993 | Disable to measure
994 | Not attempt/not done
995 | Does not answer
996 | Not applicable
997 | Refuse
998 | Do not know
999 | Missing