# Description of DataSchema variable

The description of harmonised variable is the following:

* Short name: `wealth`
* Variable label: `Total household wealth in quintiles`
* Variable description: `Total score based in all sources of income transformed into a comparable and normalized categoric variable.`
* Domain: `Socio-demographic and economic characteristics`
* Value type: `categorical ordinal`
* Category coding:

**Code** | **Category Label**
-------- | ------------------
1        | 1st quintile
2        | 2nd quintile
3        | 3rd quintile
4        | 4th quintile
5        | 5th quintile

* Category missings: 

**Code** | **Category Label**
----| ------------------
991 | CAPI/interviewer error
992 | Impute
993 | Disable to measure
994 | Not attempt/not done
995 | Does not answer
996 | Not applicable
997 | Refuse
998 | Do not know
999 | Missing

* Comments: `Need to pay attention to specificities like: before/after taxes or contributions. People: HH income is prioritized. When not available individual/caregiver/informant/family income is caolected. Source: Pension/family/work/government/disablity/total. all sources are taken into account. For some studies, the maximum value can be compared (and crossed by sex and age to control biases) . Time-lapse: weekly, monthly, in the last 12 months. 'Many values are missing since not all respondents have all sources of income or, within the household there is not always more members, in these cases do not confuse missing data with missing values and mean a 0 should be added to the total sum in each case.`
