---
title: "Sample weights"
output:
  html_document:
    highlight: tango
    number_sections: yes
    theme: united
    toc: yes
    toc_depth: 6
    toc_float:
      collapsed: yes
      smooth_scroll: yes
---

<!-- ########################################################## --> 
<!-- # Installation, loading packages -->
```{r setup, include=FALSE}
source("../../setup_iago.r")
```
<!-- ########################################################## --> 
<!-- # Loading DS description -->
```{r main, child='../../_DS_Rmd/weightsDS.Rmd'}
```
```{r global, echo=F}
source('../../_DS_Rmd/weightsDS.R')
```



# Data process



## India


### Wave 1


#### Study-specific variable description



| **Name** | `indi_wt_pooled`|
|-|-|
| **Label** | `pooled individual weight`|
| **Table name**  | `LASI-Pilot_all`|
| **Categories** | `continuous`|
| **Description** |  |

```{r assign w1, echo=F}

opal.assign.table.tibble(o, 'LASI_w1','LASI.LASI-Pilot_all',variables=list('indi_wt_pooled'), missings = T)
LASI_w1 <- opal.execute(o,'LASI_w1')

```

```{r local w1, echo=F}

vbl <- LASI_w1$indi_wt_pooled
kable(Continuous_summary(var = vbl, missing_values = NA)[3], caption = 'indi_wt_pooled')
pander(Continuous_summary(vbl, missing_values = NA)$summary, caption = "Summary")
ggplot(LASI_w1, aes(indi_wt_pooled)) + geom_bar(stat="count", width=0.01, fill="steelblue") + xlab(label(vbl)) + ylab("Frequency")

```


#### Harmonisation algorithm


**R script:**

```{r harmo w1}

# Categorical variable harmonization
LASI_ds_w1 <- tibble(id=LASI_w1$id)
LASI_ds_w1$w <- LASI_w1$indi_wt_pooled

```


#### Statistics of the new harmonized variable

```{r descript w1, echo=F}

vbl <- LASI_ds_w1$w
kable(Continuous_summary(var = vbl, missing_values = miss_values_vector)[3], caption = ds_label)
kable(Continuous_summary(vbl, missing_values = miss_values_vector)[2], caption = "Values")
pander(Continuous_summary(vbl, missing_values = miss_values_vector)$summary, caption = "Summary")
ggplot(LASI_ds_w1, aes(w)) + geom_bar(stat="count", width=0.01, fill="steelblue") + xlab(ds_label) + ylab("Frequency")

```


#### Validation

```{r crosstabulation w1, echo=F}

```







# Quality estimation


<!-- ########################################################## --> 
<!-- # Save -->
```{r save, include=FALSE, echo=F}

label(LASI_ds_w1$w) <- ds_label

l.LASI <- list(w1 = LASI_ds_w1)

for(index in seq_along(l.LASI)){
  w <- l.LASI[[index]]
  save(w, file = paste0(datafolder,names(l.LASI)[index],"/w.RData"))
}

```
<!-- ########################################################## --> 






<!-- ########################################################## -->
<!--- # Close OPAL R Session -->
```{r closeRsession, echo=FALSE}
opal.logout(o)
```





