---
title: "Living Status"
output:
  html_document:
    highlight: tango
    number_sections: yes
    theme: united
    toc: yes
    toc_depth: 6
    toc_float:
      collapsed: yes
      smooth_scroll: yes
---

<!-- ########################################################## --> 
<!-- # Installation, loading packages -->
```{r setup, include=FALSE}
source("../../setup.r")
```
<!-- ########################################################## --> 
<!-- # Loading DS description -->
```{r main, child='../../_DS_Rmd/living_statusDS.Rmd'}
```
```{r global, echo=F}
source('../../_DS_Rmd/living_statusDS.R')
```

  
# Data process




## India

### Wave 1 


```{r assign_india, echo=F}
opal.assign.table.tibble(o, 'LASI_w1','LASI.LASI-Pilot_all',
                         variables=list('dm007_year'), missings = TRUE)
LASI_w1 <- opal.execute(o,'LASI_w1')
```



#### Harmonisation algorithm
It's considered that at baseline all the individuals are alive. 


**R script:**

```{r harmo_india}
LASI_ds_w1 <- tibble(id=LASI_w1$id)
LASI_ds_w1$living_status <- 0

```

#### Statistics of the new harmonised variable
```{r descript_india, echo=F}
vari <- LASI_ds_w1$living_status
kable(Continuous_summary(var = vari, missing_values = c(991, 992, 993, 994, 995, 996, 997, 998, 999))[3], caption = ds_label)
kable(Continuous_summary(vari, missing_values = c(991, 992, 993, 994, 995, 996, 997, 998, 999))[2], caption = "Values")
pander(Continuous_summary(vari, missing_values = c(991, 992, 993, 994, 995, 996, 997, 998, 999))$summary, caption = "Summary")
ggplot(LASI_ds_w1, aes(x=factor(living_status))) + geom_bar(stat="count", width=0.4, fill="steelblue") + xlab(ds_label) + ylab("Frequency") 
```

#### Validation
```{r crosstabulation_india, echo=F}
```





```{r importOPAL_india, echo=F}


living_status <- LASI_ds_w1
save(living_status, file = "../RData/w1/living_status.RData")
rm(living_status)

```





# Quality estimation

No comments.


```{r closeRsession, echo=FALSE}
opal.logout(o)
```
