---
title: "Respondent"
output:
  html_document:
    highlight: tango
    number_sections: yes
    theme: united
    toc: yes
    toc_depth: 6
    toc_float:
      collapsed: yes
      smooth_scroll: yes
---

<!-- ########################################################## --> 
<!-- # Installation, loading packages -->
```{r setup, include=FALSE}
source("../../setup.r")
```
<!-- ########################################################## --> 

<!-- ########################################################## --> 
<!-- # Loading DS description -->
```{r main, child='../../_DS_Rmd/respondentDS.Rmd'}
```

```{r global, echo=F}
source('../../_DS_Rmd/respondentDS.R')
```


# Data process

## SHARE



```{r assign, echo=F}

opal.assign.table.tibble(o, 'SHARE_w1','SHARE.sharew1_rel2-6-0_dn',variables=list('hhid1'), missings = T)
SHARE_w1 <- opal.execute(o,'SHARE_w1')

opal.assign.table.tibble(o, 'SHARE_w2','SHARE.sharew2_rel2-6-0_mh',variables=list('hhid2'), missings = T)
SHARE_w2 <- opal.execute(o,'SHARE_w2')

opal.assign.table.tibble(o, 'SHARE_w3_gv','SHARE.sharew3_rel1_gv_weights',variables=list('hhid3'), missings = T)
SHARE_w3_gv <- opal.execute(o,'SHARE_w3_gv')

opal.assign.table.tibble(o, 'SHARE_w3_cv','SHARE.sharew3_rel1_cv_r_without_noint',variables=list('hhid3'), missings = T)
SHARE_w3_cv <- opal.execute(o,'SHARE_w3_cv')

SHARE_w3 <- full_join(SHARE_w3_gv,SHARE_w3_cv,by="id", suffix=c(".gv",".cv"))

opal.assign.table.tibble(o, 'SHARE_w4','SHARE.sharew4_rel1-1-1_cv_r_without_noint',variables=list('hhid4'), missings = T)
SHARE_w4 <- opal.execute(o,'SHARE_w4')

opal.assign.table.tibble(o, 'SHARE_w5','SHARE.sharew5_rel1-0-0_cv_r_without_noint',variables=list('hhid5'), missings = T)
SHARE_w5 <- opal.execute(o,'SHARE_w5')


```


#### Harmonisation algorithm

All the interviewed individuals are considered as participants. 

**R script:**

```{r harmo}

rm(list=setdiff(ls(), c("o","datafolder","SHARE_w1","SHARE_w2","SHARE_w3","SHARE_w4","SHARE_w5","ds_label","cat_label") )) 

dflist <- lapply(Filter(function(x) is.data.frame(get(x)), ls()), get)



ind <- 0
for(df in dflist){
  ind <- ind + 1
  respondent <- tibble(id=df$id)
  respondent$respondent <- 0
  respondent$respondent <- labelled(respondent$respondent, labels = cat_label)
  label(respondent$respondent) <- ds_label
  save(respondent,file = paste0("../RData/w",as.character(ind),"/respondent.RData"))
}

```



# Quality estimation

All eligible household members are participants, and there is no information specifying their relationship.






<!-- ########################################################## -->
<!--- # Close OPAL R Session -->
```{r closeRsession, echo=FALSE}
opal.logout(o)
```





